---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - name: httpbin
          image: nginx  # kennethreitz/httpbin
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  selector:
    app: httpbin
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: keycloak-integration
  namespace: default
spec:
  http:
  - name: nginx
    match:
      hosts:
      - http-172.18.0.2.nip.io
      paths:
      - /*
    backends:
    - serviceName: httpbin
      servicePort: 80
      weight: 100
    # - serviceName: httpbin
    #   servicePort: 80
    #   weight: 30
    plugins:
    - name: proxy-rewrite
      enable: true
      config:
        uri: "/"
    - name: openid-connect
      enable: true
      config:
        client_id: apisix
        client_secret: 9DBttiW1NJZnoP9eNOeqvKP1AKUHVNMM
        discovery: http://keycloak-172.18.0.2.nip.io/auth/realms/apisix/.well-known/openid-configuration
        scope: openid profile
        bearer_only: false
        session:
          secret: 3DOqn2p6+iq4GPaG264tt0Tt6NZG2uQyDplhVcz9VCA=
        realm: apisix
        introspection_endpoint_auth_method: client_secret_post
        redirect_uri: "/.apisix/redirect"  # this should be added to Keycloak > Clients > Access settings > Valid redirect URIs: http://http2-172.18.0.2.nip.io/.apisix/redirect
